########################################################
#port 0
set_property PACKAGE_PIN N17 [get_ports {rgmii_td[0]}]
set_property PACKAGE_PIN N18 [get_ports {rgmii_td[1]}]
set_property PACKAGE_PIN N19 [get_ports {rgmii_td[2]}]
set_property PACKAGE_PIN N20 [get_ports {rgmii_td[3]}]
set_property PACKAGE_PIN J17 [get_ports mdio_mdc]
set_property PACKAGE_PIN J16 [get_ports mdio_mdio_io]
set_property PACKAGE_PIN L19 [get_ports phy_reset_n]
set_property PACKAGE_PIN K19 [get_ports rgmii_rxc]
set_property PACKAGE_PIN K20 [get_ports rgmii_rx_ctl]
set_property PACKAGE_PIN J18 [get_ports {rgmii_rd[0]}]
set_property PACKAGE_PIN K18 [get_ports {rgmii_rd[1]}]
set_property PACKAGE_PIN J15 [get_ports {rgmii_rd[2]}]
set_property PACKAGE_PIN K15 [get_ports {rgmii_rd[3]}]
set_property PACKAGE_PIN R21 [get_ports rgmii_txc]
set_property PACKAGE_PIN R20 [get_ports rgmii_tx_ctl]

set_property IOSTANDARD LVCMOS33 [get_ports mdio_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports phy_reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[3]}]


set_property SLEW FAST [get_ports rgmii_tx_ctl]
set_property SLEW FAST [get_ports rgmii_txc]
set_property SLEW FAST [get_ports {rgmii_td[3]}]
set_property SLEW FAST [get_ports {rgmii_td[2]}]
set_property SLEW FAST [get_ports {rgmii_td[1]}]
set_property SLEW FAST [get_ports {rgmii_td[0]}]
set_property SLEW SLOW [get_ports phy_reset_n]


############## clock and reset define##################
set_property PACKAGE_PIN A17 [get_ports rst_n]
set_property PACKAGE_PIN Y9 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property UNAVAILABLE_DURING_CALIBRATION true [get_ports mdio_mdio_io]

create_clock -period 20.000 -name sys_clk -waveform {0.000 10.000} [get_ports sys_clk]
create_clock -period 8.000 -name RGMII_RXC_0 -waveform {0.000 4.000} [get_ports rgmii_rxc]
create_clock -period 8.000 -name RGMII_TXC_0 -waveform {0.000 4.000} [get_ports rgmii_txc]

set_input_delay -clock RGMII_RXC_0 -min -add_delay -1.700 [get_ports {{rgmii_rd[0]} {rgmii_rd[1]} {rgmii_rd[2]} {rgmii_rd[3]} rgmii_rx_ctl}]
set_input_delay -clock RGMII_RXC_0 -max -add_delay -0.700 [get_ports {{rgmii_rd[0]} {rgmii_rd[1]} {rgmii_rd[2]} {rgmii_rd[3]} rgmii_rx_ctl}]
set_input_delay -clock RGMII_RXC_0 -clock_fall -min -add_delay -1.700 [get_ports {{rgmii_rd[0]} {rgmii_rd[1]} {rgmii_rd[2]} {rgmii_rd[3]} rgmii_rx_ctl}]
set_input_delay -clock RGMII_RXC_0 -clock_fall -max -add_delay -0.700 [get_ports {{rgmii_rd[0]} {rgmii_rd[1]} {rgmii_rd[2]} {rgmii_rd[3]} rgmii_rx_ctl}]

set_output_delay -clock RGMII_TXC_0 -min -add_delay -0.500 [get_ports {{rgmii_td[0]} {rgmii_td[1]} {rgmii_td[2]} {rgmii_td[3]} rgmii_tx_ctl}]
set_output_delay -clock RGMII_TXC_0 -max -add_delay 1.000 [get_ports {{rgmii_td[0]} {rgmii_td[1]} {rgmii_td[2]} {rgmii_td[3]} rgmii_tx_ctl}]
set_output_delay -clock RGMII_TXC_0 -clock_fall -min -add_delay -0.500 [get_ports {{rgmii_td[0]} {rgmii_td[1]} {rgmii_td[2]} {rgmii_td[3]} rgmii_tx_ctl}]
set_output_delay -clock RGMII_TXC_0 -clock_fall -max -add_delay 1.000 [get_ports {{rgmii_td[0]} {rgmii_td[1]} {rgmii_td[2]} {rgmii_td[3]} rgmii_tx_ctl}]

############## usb uart define########################
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property PACKAGE_PIN Y20 [get_ports uart_rx]
#set_property PACKAGE_PIN V12 [get_ports uart_rx]

set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property PACKAGE_PIN AB21 [get_ports uart_tx]
#set_property PACKAGE_PIN U12 [get_ports uart_tx]

set_property IOSTANDARD LVCMOS33 [get_ports uart_cts]
set_property PACKAGE_PIN W20 [get_ports uart_cts]
#set_property PACKAGE_PIN U9 [get_ports uart_cts]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rts]
set_property PACKAGE_PIN V22 [get_ports uart_rts]
#set_property PACKAGE_PIN T6 [get_ports uart_rts]


############## led ###################################
set_property PACKAGE_PIN A16 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports led]

############## CAN define#############################
#set_property PACKAGE_PIN R18 [get_ports {can_ad[0]}]
#set_property PACKAGE_PIN L17 [get_ports {can_ad[1]}]
#set_property PACKAGE_PIN R16 [get_ports {can_ad[2]}]
#set_property PACKAGE_PIN J20 [get_ports {can_ad[3]}]
#set_property PACKAGE_PIN J22 [get_ports {can_ad[4]}]
#set_property PACKAGE_PIN AA19 [get_ports {can_ad[5]}]
#set_property PACKAGE_PIN V20 [get_ports {can_ad[6]}]
#set_property PACKAGE_PIN U21 [get_ports {can_ad[7]}]
#set_property PACKAGE_PIN P21 [get_ports can_oe_n]
#set_property PACKAGE_PIN R19 [get_ports can_dir]

#set_property PACKAGE_PIN K21 [get_ports can_cs_n]
#set_property PACKAGE_PIN Y19 [get_ports can_wr_n]
#set_property PACKAGE_PIN T21 [get_ports can_rst_n]
#set_property PACKAGE_PIN P16 [get_ports can_ale]
#set_property PACKAGE_PIN J21 [get_ports can_rd_n]
#set_property PACKAGE_PIN U20 [get_ports can_mode]
#set_property PACKAGE_PIN M17 [get_ports can_int_n]

#set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports can_oe_n]
#set_property IOSTANDARD LVCMOS33 [get_ports can_dir]

#set_property IOSTANDARD LVCMOS33 [get_ports can_cs_n]
#set_property IOSTANDARD LVCMOS33 [get_ports can_ale]
#set_property IOSTANDARD LVCMOS33 [get_ports can_wr_n]
#set_property IOSTANDARD LVCMOS33 [get_ports can_rd_n]
#set_property IOSTANDARD LVCMOS33 [get_ports can_int_n]
#set_property IOSTANDARD LVCMOS33 [get_ports can_rst_n]
#set_property IOSTANDARD LVCMOS33 [get_ports can_mode]

############## LCD define#############################
#set_property PACKAGE_PIN V12 [get_ports {lcd_r[0]}]
#set_property PACKAGE_PIN W12 [get_ports {lcd_r[1]}]
#set_property PACKAGE_PIN U12 [get_ports {lcd_r[2]}]
#set_property PACKAGE_PIN U11 [get_ports {lcd_r[3]}]
#set_property PACKAGE_PIN U9 [get_ports {lcd_r[4]}]
#set_property PACKAGE_PIN U10 [get_ports {lcd_r[5]}]
#set_property PACKAGE_PIN T6 [get_ports {lcd_r[6]}]
#set_property PACKAGE_PIN R6 [get_ports {lcd_r[7]}]
#set_property PACKAGE_PIN U5 [get_ports {lcd_g[0]}]
#set_property PACKAGE_PIN U6 [get_ports {lcd_g[1]}]
#set_property PACKAGE_PIN U4 [get_ports {lcd_g[2]}]
#set_property PACKAGE_PIN T4 [get_ports {lcd_g[3]}]
#set_property PACKAGE_PIN W10 [get_ports {lcd_g[4]}]
#set_property PACKAGE_PIN W11 [get_ports {lcd_g[5]}]
#set_property PACKAGE_PIN Y10 [get_ports {lcd_g[6]}]
#set_property PACKAGE_PIN Y11 [get_ports {lcd_g[7]}]
#set_property PACKAGE_PIN W8 [get_ports {lcd_b[0]}]
#set_property PACKAGE_PIN V8 [get_ports {lcd_b[1]}]
#set_property PACKAGE_PIN AA6 [get_ports {lcd_b[2]}]
#set_property PACKAGE_PIN AA7 [get_ports {lcd_b[3]}]
#set_property PACKAGE_PIN AA11 [get_ports {lcd_b[4]}]
#set_property PACKAGE_PIN AB11 [get_ports {lcd_b[5]}]
#set_property PACKAGE_PIN AB4 [get_ports {lcd_b[6]}]
#set_property PACKAGE_PIN AB5 [get_ports {lcd_b[7]}]
#set_property PACKAGE_PIN AB1 [get_ports lcd_dclk]
#set_property PACKAGE_PIN AB2 [get_ports lcd_hs]
#set_property PACKAGE_PIN Y4 [get_ports lcd_vs]
#set_property PACKAGE_PIN AA4 [get_ports lcd_de]

#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports lcd_dclk]
#set_property IOSTANDARD LVCMOS33 [get_ports lcd_hs]
#set_property IOSTANDARD LVCMOS33 [get_ports lcd_vs]
#set_property IOSTANDARD LVCMOS33 [get_ports lcd_de]

############## rs485 define########################
set_property IOSTANDARD LVCMOS33 [get_ports rs485_rx_0]
set_property PACKAGE_PIN U12 [get_ports rs485_rx_0]
set_property IOSTANDARD LVCMOS33 [get_ports rs485_tx_0]
set_property PACKAGE_PIN U9 [get_ports rs485_tx_0]
set_property IOSTANDARD LVCMOS33 [get_ports rs485_de_0]
set_property PACKAGE_PIN T6 [get_ports rs485_de_0]

set_property IOSTANDARD LVCMOS33 [get_ports rs485_rx_1]
set_property PACKAGE_PIN U5 [get_ports rs485_rx_1]
set_property IOSTANDARD LVCMOS33 [get_ports rs485_tx_1]
set_property PACKAGE_PIN U4 [get_ports rs485_tx_1]
set_property IOSTANDARD LVCMOS33 [get_ports rs485_de_1]
set_property PACKAGE_PIN W10 [get_ports rs485_de_1]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_to_125m/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {UMforCPU/timelyRV_top/mem_rdata_mem[0]} {UMforCPU/timelyRV_top/mem_rdata_mem[1]} {UMforCPU/timelyRV_top/mem_rdata_mem[2]} {UMforCPU/timelyRV_top/mem_rdata_mem[3]} {UMforCPU/timelyRV_top/mem_rdata_mem[4]} {UMforCPU/timelyRV_top/mem_rdata_mem[5]} {UMforCPU/timelyRV_top/mem_rdata_mem[6]} {UMforCPU/timelyRV_top/mem_rdata_mem[7]} {UMforCPU/timelyRV_top/mem_rdata_mem[8]} {UMforCPU/timelyRV_top/mem_rdata_mem[9]} {UMforCPU/timelyRV_top/mem_rdata_mem[10]} {UMforCPU/timelyRV_top/mem_rdata_mem[11]} {UMforCPU/timelyRV_top/mem_rdata_mem[12]} {UMforCPU/timelyRV_top/mem_rdata_mem[13]} {UMforCPU/timelyRV_top/mem_rdata_mem[14]} {UMforCPU/timelyRV_top/mem_rdata_mem[15]} {UMforCPU/timelyRV_top/mem_rdata_mem[16]} {UMforCPU/timelyRV_top/mem_rdata_mem[17]} {UMforCPU/timelyRV_top/mem_rdata_mem[18]} {UMforCPU/timelyRV_top/mem_rdata_mem[19]} {UMforCPU/timelyRV_top/mem_rdata_mem[20]} {UMforCPU/timelyRV_top/mem_rdata_mem[21]} {UMforCPU/timelyRV_top/mem_rdata_mem[22]} {UMforCPU/timelyRV_top/mem_rdata_mem[23]} {UMforCPU/timelyRV_top/mem_rdata_mem[24]} {UMforCPU/timelyRV_top/mem_rdata_mem[25]} {UMforCPU/timelyRV_top/mem_rdata_mem[26]} {UMforCPU/timelyRV_top/mem_rdata_mem[27]} {UMforCPU/timelyRV_top/mem_rdata_mem[28]} {UMforCPU/timelyRV_top/mem_rdata_mem[29]} {UMforCPU/timelyRV_top/mem_rdata_mem[30]} {UMforCPU/timelyRV_top/mem_rdata_mem[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 30 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {UMforCPU/timelyRV_top/mem_addr_test[0]} {UMforCPU/timelyRV_top/mem_addr_test[1]} {UMforCPU/timelyRV_top/mem_addr_test[2]} {UMforCPU/timelyRV_top/mem_addr_test[3]} {UMforCPU/timelyRV_top/mem_addr_test[4]} {UMforCPU/timelyRV_top/mem_addr_test[5]} {UMforCPU/timelyRV_top/mem_addr_test[6]} {UMforCPU/timelyRV_top/mem_addr_test[7]} {UMforCPU/timelyRV_top/mem_addr_test[8]} {UMforCPU/timelyRV_top/mem_addr_test[9]} {UMforCPU/timelyRV_top/mem_addr_test[10]} {UMforCPU/timelyRV_top/mem_addr_test[11]} {UMforCPU/timelyRV_top/mem_addr_test[12]} {UMforCPU/timelyRV_top/mem_addr_test[13]} {UMforCPU/timelyRV_top/mem_addr_test[14]} {UMforCPU/timelyRV_top/mem_addr_test[15]} {UMforCPU/timelyRV_top/mem_addr_test[16]} {UMforCPU/timelyRV_top/mem_addr_test[17]} {UMforCPU/timelyRV_top/mem_addr_test[18]} {UMforCPU/timelyRV_top/mem_addr_test[19]} {UMforCPU/timelyRV_top/mem_addr_test[20]} {UMforCPU/timelyRV_top/mem_addr_test[21]} {UMforCPU/timelyRV_top/mem_addr_test[22]} {UMforCPU/timelyRV_top/mem_addr_test[23]} {UMforCPU/timelyRV_top/mem_addr_test[24]} {UMforCPU/timelyRV_top/mem_addr_test[25]} {UMforCPU/timelyRV_top/mem_addr_test[26]} {UMforCPU/timelyRV_top/mem_addr_test[27]} {UMforCPU/timelyRV_top/mem_addr_test[28]} {UMforCPU/timelyRV_top/mem_addr_test[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {UMforCPU/timelyRV_top/mem_rdata[0]} {UMforCPU/timelyRV_top/mem_rdata[1]} {UMforCPU/timelyRV_top/mem_rdata[2]} {UMforCPU/timelyRV_top/mem_rdata[3]} {UMforCPU/timelyRV_top/mem_rdata[4]} {UMforCPU/timelyRV_top/mem_rdata[5]} {UMforCPU/timelyRV_top/mem_rdata[6]} {UMforCPU/timelyRV_top/mem_rdata[7]} {UMforCPU/timelyRV_top/mem_rdata[8]} {UMforCPU/timelyRV_top/mem_rdata[9]} {UMforCPU/timelyRV_top/mem_rdata[10]} {UMforCPU/timelyRV_top/mem_rdata[11]} {UMforCPU/timelyRV_top/mem_rdata[12]} {UMforCPU/timelyRV_top/mem_rdata[13]} {UMforCPU/timelyRV_top/mem_rdata[14]} {UMforCPU/timelyRV_top/mem_rdata[15]} {UMforCPU/timelyRV_top/mem_rdata[16]} {UMforCPU/timelyRV_top/mem_rdata[17]} {UMforCPU/timelyRV_top/mem_rdata[18]} {UMforCPU/timelyRV_top/mem_rdata[19]} {UMforCPU/timelyRV_top/mem_rdata[20]} {UMforCPU/timelyRV_top/mem_rdata[21]} {UMforCPU/timelyRV_top/mem_rdata[22]} {UMforCPU/timelyRV_top/mem_rdata[23]} {UMforCPU/timelyRV_top/mem_rdata[24]} {UMforCPU/timelyRV_top/mem_rdata[25]} {UMforCPU/timelyRV_top/mem_rdata[26]} {UMforCPU/timelyRV_top/mem_rdata[27]} {UMforCPU/timelyRV_top/mem_rdata[28]} {UMforCPU/timelyRV_top/mem_rdata[29]} {UMforCPU/timelyRV_top/mem_rdata[30]} {UMforCPU/timelyRV_top/mem_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {UMforCPU/timelyRV_top/mem_wstrb[0]} {UMforCPU/timelyRV_top/mem_wstrb[1]} {UMforCPU/timelyRV_top/mem_wstrb[2]} {UMforCPU/timelyRV_top/mem_wstrb[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {UMforCPU/timelyRV_top/mem_addr[0]} {UMforCPU/timelyRV_top/mem_addr[1]} {UMforCPU/timelyRV_top/mem_addr[2]} {UMforCPU/timelyRV_top/mem_addr[3]} {UMforCPU/timelyRV_top/mem_addr[4]} {UMforCPU/timelyRV_top/mem_addr[5]} {UMforCPU/timelyRV_top/mem_addr[6]} {UMforCPU/timelyRV_top/mem_addr[7]} {UMforCPU/timelyRV_top/mem_addr[8]} {UMforCPU/timelyRV_top/mem_addr[9]} {UMforCPU/timelyRV_top/mem_addr[10]} {UMforCPU/timelyRV_top/mem_addr[11]} {UMforCPU/timelyRV_top/mem_addr[12]} {UMforCPU/timelyRV_top/mem_addr[13]} {UMforCPU/timelyRV_top/mem_addr[14]} {UMforCPU/timelyRV_top/mem_addr[15]} {UMforCPU/timelyRV_top/mem_addr[16]} {UMforCPU/timelyRV_top/mem_addr[17]} {UMforCPU/timelyRV_top/mem_addr[18]} {UMforCPU/timelyRV_top/mem_addr[19]} {UMforCPU/timelyRV_top/mem_addr[20]} {UMforCPU/timelyRV_top/mem_addr[21]} {UMforCPU/timelyRV_top/mem_addr[22]} {UMforCPU/timelyRV_top/mem_addr[23]} {UMforCPU/timelyRV_top/mem_addr[24]} {UMforCPU/timelyRV_top/mem_addr[25]} {UMforCPU/timelyRV_top/mem_addr[26]} {UMforCPU/timelyRV_top/mem_addr[27]} {UMforCPU/timelyRV_top/mem_addr[28]} {UMforCPU/timelyRV_top/mem_addr[29]} {UMforCPU/timelyRV_top/mem_addr[30]} {UMforCPU/timelyRV_top/mem_addr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {UMforCPU/timelyRV_top/mem_wdata[0]} {UMforCPU/timelyRV_top/mem_wdata[1]} {UMforCPU/timelyRV_top/mem_wdata[2]} {UMforCPU/timelyRV_top/mem_wdata[3]} {UMforCPU/timelyRV_top/mem_wdata[4]} {UMforCPU/timelyRV_top/mem_wdata[5]} {UMforCPU/timelyRV_top/mem_wdata[6]} {UMforCPU/timelyRV_top/mem_wdata[7]} {UMforCPU/timelyRV_top/mem_wdata[8]} {UMforCPU/timelyRV_top/mem_wdata[9]} {UMforCPU/timelyRV_top/mem_wdata[10]} {UMforCPU/timelyRV_top/mem_wdata[11]} {UMforCPU/timelyRV_top/mem_wdata[12]} {UMforCPU/timelyRV_top/mem_wdata[13]} {UMforCPU/timelyRV_top/mem_wdata[14]} {UMforCPU/timelyRV_top/mem_wdata[15]} {UMforCPU/timelyRV_top/mem_wdata[16]} {UMforCPU/timelyRV_top/mem_wdata[17]} {UMforCPU/timelyRV_top/mem_wdata[18]} {UMforCPU/timelyRV_top/mem_wdata[19]} {UMforCPU/timelyRV_top/mem_wdata[20]} {UMforCPU/timelyRV_top/mem_wdata[21]} {UMforCPU/timelyRV_top/mem_wdata[22]} {UMforCPU/timelyRV_top/mem_wdata[23]} {UMforCPU/timelyRV_top/mem_wdata[24]} {UMforCPU/timelyRV_top/mem_wdata[25]} {UMforCPU/timelyRV_top/mem_wdata[26]} {UMforCPU/timelyRV_top/mem_wdata[27]} {UMforCPU/timelyRV_top/mem_wdata[28]} {UMforCPU/timelyRV_top/mem_wdata[29]} {UMforCPU/timelyRV_top/mem_wdata[30]} {UMforCPU/timelyRV_top/mem_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 96 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {UMforCPU/din_32b_p[0]} {UMforCPU/din_32b_p[1]} {UMforCPU/din_32b_p[2]} {UMforCPU/din_32b_p[3]} {UMforCPU/din_32b_p[4]} {UMforCPU/din_32b_p[5]} {UMforCPU/din_32b_p[6]} {UMforCPU/din_32b_p[7]} {UMforCPU/din_32b_p[8]} {UMforCPU/din_32b_p[9]} {UMforCPU/din_32b_p[10]} {UMforCPU/din_32b_p[11]} {UMforCPU/din_32b_p[12]} {UMforCPU/din_32b_p[13]} {UMforCPU/din_32b_p[14]} {UMforCPU/din_32b_p[15]} {UMforCPU/din_32b_p[16]} {UMforCPU/din_32b_p[17]} {UMforCPU/din_32b_p[18]} {UMforCPU/din_32b_p[19]} {UMforCPU/din_32b_p[20]} {UMforCPU/din_32b_p[21]} {UMforCPU/din_32b_p[22]} {UMforCPU/din_32b_p[23]} {UMforCPU/din_32b_p[24]} {UMforCPU/din_32b_p[25]} {UMforCPU/din_32b_p[26]} {UMforCPU/din_32b_p[27]} {UMforCPU/din_32b_p[28]} {UMforCPU/din_32b_p[29]} {UMforCPU/din_32b_p[30]} {UMforCPU/din_32b_p[31]} {UMforCPU/din_32b_p[32]} {UMforCPU/din_32b_p[33]} {UMforCPU/din_32b_p[34]} {UMforCPU/din_32b_p[35]} {UMforCPU/din_32b_p[36]} {UMforCPU/din_32b_p[37]} {UMforCPU/din_32b_p[38]} {UMforCPU/din_32b_p[39]} {UMforCPU/din_32b_p[40]} {UMforCPU/din_32b_p[41]} {UMforCPU/din_32b_p[42]} {UMforCPU/din_32b_p[43]} {UMforCPU/din_32b_p[44]} {UMforCPU/din_32b_p[45]} {UMforCPU/din_32b_p[46]} {UMforCPU/din_32b_p[47]} {UMforCPU/din_32b_p[48]} {UMforCPU/din_32b_p[49]} {UMforCPU/din_32b_p[50]} {UMforCPU/din_32b_p[51]} {UMforCPU/din_32b_p[52]} {UMforCPU/din_32b_p[53]} {UMforCPU/din_32b_p[54]} {UMforCPU/din_32b_p[55]} {UMforCPU/din_32b_p[56]} {UMforCPU/din_32b_p[57]} {UMforCPU/din_32b_p[58]} {UMforCPU/din_32b_p[59]} {UMforCPU/din_32b_p[60]} {UMforCPU/din_32b_p[61]} {UMforCPU/din_32b_p[62]} {UMforCPU/din_32b_p[63]} {UMforCPU/din_32b_p[64]} {UMforCPU/din_32b_p[65]} {UMforCPU/din_32b_p[66]} {UMforCPU/din_32b_p[67]} {UMforCPU/din_32b_p[68]} {UMforCPU/din_32b_p[69]} {UMforCPU/din_32b_p[70]} {UMforCPU/din_32b_p[71]} {UMforCPU/din_32b_p[72]} {UMforCPU/din_32b_p[73]} {UMforCPU/din_32b_p[74]} {UMforCPU/din_32b_p[75]} {UMforCPU/din_32b_p[76]} {UMforCPU/din_32b_p[77]} {UMforCPU/din_32b_p[78]} {UMforCPU/din_32b_p[79]} {UMforCPU/din_32b_p[80]} {UMforCPU/din_32b_p[81]} {UMforCPU/din_32b_p[82]} {UMforCPU/din_32b_p[83]} {UMforCPU/din_32b_p[84]} {UMforCPU/din_32b_p[85]} {UMforCPU/din_32b_p[86]} {UMforCPU/din_32b_p[87]} {UMforCPU/din_32b_p[88]} {UMforCPU/din_32b_p[89]} {UMforCPU/din_32b_p[90]} {UMforCPU/din_32b_p[91]} {UMforCPU/din_32b_p[92]} {UMforCPU/din_32b_p[93]} {UMforCPU/din_32b_p[94]} {UMforCPU/din_32b_p[95]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 3 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {UMforCPU/interrupt_p[0]} {UMforCPU/interrupt_p[1]} {UMforCPU/interrupt_p[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 3 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {UMforCPU/rden_p[0]} {UMforCPU/rden_p[1]} {UMforCPU/rden_p[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {UMforCPU/peri_addr[0]} {UMforCPU/peri_addr[1]} {UMforCPU/peri_addr[2]} {UMforCPU/peri_addr[3]} {UMforCPU/peri_addr[4]} {UMforCPU/peri_addr[5]} {UMforCPU/peri_addr[6]} {UMforCPU/peri_addr[7]} {UMforCPU/peri_addr[8]} {UMforCPU/peri_addr[9]} {UMforCPU/peri_addr[10]} {UMforCPU/peri_addr[11]} {UMforCPU/peri_addr[12]} {UMforCPU/peri_addr[13]} {UMforCPU/peri_addr[14]} {UMforCPU/peri_addr[15]} {UMforCPU/peri_addr[16]} {UMforCPU/peri_addr[17]} {UMforCPU/peri_addr[18]} {UMforCPU/peri_addr[19]} {UMforCPU/peri_addr[20]} {UMforCPU/peri_addr[21]} {UMforCPU/peri_addr[22]} {UMforCPU/peri_addr[23]} {UMforCPU/peri_addr[24]} {UMforCPU/peri_addr[25]} {UMforCPU/peri_addr[26]} {UMforCPU/peri_addr[27]} {UMforCPU/peri_addr[28]} {UMforCPU/peri_addr[29]} {UMforCPU/peri_addr[30]} {UMforCPU/peri_addr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {UMforCPU/irq_bitmap[0]} {UMforCPU/irq_bitmap[1]} {UMforCPU/irq_bitmap[2]} {UMforCPU/irq_bitmap[3]} {UMforCPU/irq_bitmap[4]} {UMforCPU/irq_bitmap[5]} {UMforCPU/irq_bitmap[6]} {UMforCPU/irq_bitmap[7]} {UMforCPU/irq_bitmap[8]} {UMforCPU/irq_bitmap[9]} {UMforCPU/irq_bitmap[10]} {UMforCPU/irq_bitmap[11]} {UMforCPU/irq_bitmap[12]} {UMforCPU/irq_bitmap[13]} {UMforCPU/irq_bitmap[14]} {UMforCPU/irq_bitmap[15]} {UMforCPU/irq_bitmap[16]} {UMforCPU/irq_bitmap[17]} {UMforCPU/irq_bitmap[18]} {UMforCPU/irq_bitmap[19]} {UMforCPU/irq_bitmap[20]} {UMforCPU/irq_bitmap[21]} {UMforCPU/irq_bitmap[22]} {UMforCPU/irq_bitmap[23]} {UMforCPU/irq_bitmap[24]} {UMforCPU/irq_bitmap[25]} {UMforCPU/irq_bitmap[26]} {UMforCPU/irq_bitmap[27]} {UMforCPU/irq_bitmap[28]} {UMforCPU/irq_bitmap[29]} {UMforCPU/irq_bitmap[30]} {UMforCPU/irq_bitmap[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 96 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {UMforCPU/addr_32b_p[0]} {UMforCPU/addr_32b_p[1]} {UMforCPU/addr_32b_p[2]} {UMforCPU/addr_32b_p[3]} {UMforCPU/addr_32b_p[4]} {UMforCPU/addr_32b_p[5]} {UMforCPU/addr_32b_p[6]} {UMforCPU/addr_32b_p[7]} {UMforCPU/addr_32b_p[8]} {UMforCPU/addr_32b_p[9]} {UMforCPU/addr_32b_p[10]} {UMforCPU/addr_32b_p[11]} {UMforCPU/addr_32b_p[12]} {UMforCPU/addr_32b_p[13]} {UMforCPU/addr_32b_p[14]} {UMforCPU/addr_32b_p[15]} {UMforCPU/addr_32b_p[16]} {UMforCPU/addr_32b_p[17]} {UMforCPU/addr_32b_p[18]} {UMforCPU/addr_32b_p[19]} {UMforCPU/addr_32b_p[20]} {UMforCPU/addr_32b_p[21]} {UMforCPU/addr_32b_p[22]} {UMforCPU/addr_32b_p[23]} {UMforCPU/addr_32b_p[24]} {UMforCPU/addr_32b_p[25]} {UMforCPU/addr_32b_p[26]} {UMforCPU/addr_32b_p[27]} {UMforCPU/addr_32b_p[28]} {UMforCPU/addr_32b_p[29]} {UMforCPU/addr_32b_p[30]} {UMforCPU/addr_32b_p[31]} {UMforCPU/addr_32b_p[32]} {UMforCPU/addr_32b_p[33]} {UMforCPU/addr_32b_p[34]} {UMforCPU/addr_32b_p[35]} {UMforCPU/addr_32b_p[36]} {UMforCPU/addr_32b_p[37]} {UMforCPU/addr_32b_p[38]} {UMforCPU/addr_32b_p[39]} {UMforCPU/addr_32b_p[40]} {UMforCPU/addr_32b_p[41]} {UMforCPU/addr_32b_p[42]} {UMforCPU/addr_32b_p[43]} {UMforCPU/addr_32b_p[44]} {UMforCPU/addr_32b_p[45]} {UMforCPU/addr_32b_p[46]} {UMforCPU/addr_32b_p[47]} {UMforCPU/addr_32b_p[48]} {UMforCPU/addr_32b_p[49]} {UMforCPU/addr_32b_p[50]} {UMforCPU/addr_32b_p[51]} {UMforCPU/addr_32b_p[52]} {UMforCPU/addr_32b_p[53]} {UMforCPU/addr_32b_p[54]} {UMforCPU/addr_32b_p[55]} {UMforCPU/addr_32b_p[56]} {UMforCPU/addr_32b_p[57]} {UMforCPU/addr_32b_p[58]} {UMforCPU/addr_32b_p[59]} {UMforCPU/addr_32b_p[60]} {UMforCPU/addr_32b_p[61]} {UMforCPU/addr_32b_p[62]} {UMforCPU/addr_32b_p[63]} {UMforCPU/addr_32b_p[64]} {UMforCPU/addr_32b_p[65]} {UMforCPU/addr_32b_p[66]} {UMforCPU/addr_32b_p[67]} {UMforCPU/addr_32b_p[68]} {UMforCPU/addr_32b_p[69]} {UMforCPU/addr_32b_p[70]} {UMforCPU/addr_32b_p[71]} {UMforCPU/addr_32b_p[72]} {UMforCPU/addr_32b_p[73]} {UMforCPU/addr_32b_p[74]} {UMforCPU/addr_32b_p[75]} {UMforCPU/addr_32b_p[76]} {UMforCPU/addr_32b_p[77]} {UMforCPU/addr_32b_p[78]} {UMforCPU/addr_32b_p[79]} {UMforCPU/addr_32b_p[80]} {UMforCPU/addr_32b_p[81]} {UMforCPU/addr_32b_p[82]} {UMforCPU/addr_32b_p[83]} {UMforCPU/addr_32b_p[84]} {UMforCPU/addr_32b_p[85]} {UMforCPU/addr_32b_p[86]} {UMforCPU/addr_32b_p[87]} {UMforCPU/addr_32b_p[88]} {UMforCPU/addr_32b_p[89]} {UMforCPU/addr_32b_p[90]} {UMforCPU/addr_32b_p[91]} {UMforCPU/addr_32b_p[92]} {UMforCPU/addr_32b_p[93]} {UMforCPU/addr_32b_p[94]} {UMforCPU/addr_32b_p[95]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 3 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {UMforCPU/dout_32b_valid_p[0]} {UMforCPU/dout_32b_valid_p[1]} {UMforCPU/dout_32b_valid_p[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {UMforCPU/peri_rdata[0]} {UMforCPU/peri_rdata[1]} {UMforCPU/peri_rdata[2]} {UMforCPU/peri_rdata[3]} {UMforCPU/peri_rdata[4]} {UMforCPU/peri_rdata[5]} {UMforCPU/peri_rdata[6]} {UMforCPU/peri_rdata[7]} {UMforCPU/peri_rdata[8]} {UMforCPU/peri_rdata[9]} {UMforCPU/peri_rdata[10]} {UMforCPU/peri_rdata[11]} {UMforCPU/peri_rdata[12]} {UMforCPU/peri_rdata[13]} {UMforCPU/peri_rdata[14]} {UMforCPU/peri_rdata[15]} {UMforCPU/peri_rdata[16]} {UMforCPU/peri_rdata[17]} {UMforCPU/peri_rdata[18]} {UMforCPU/peri_rdata[19]} {UMforCPU/peri_rdata[20]} {UMforCPU/peri_rdata[21]} {UMforCPU/peri_rdata[22]} {UMforCPU/peri_rdata[23]} {UMforCPU/peri_rdata[24]} {UMforCPU/peri_rdata[25]} {UMforCPU/peri_rdata[26]} {UMforCPU/peri_rdata[27]} {UMforCPU/peri_rdata[28]} {UMforCPU/peri_rdata[29]} {UMforCPU/peri_rdata[30]} {UMforCPU/peri_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {UMforCPU/peri_wdata[0]} {UMforCPU/peri_wdata[1]} {UMforCPU/peri_wdata[2]} {UMforCPU/peri_wdata[3]} {UMforCPU/peri_wdata[4]} {UMforCPU/peri_wdata[5]} {UMforCPU/peri_wdata[6]} {UMforCPU/peri_wdata[7]} {UMforCPU/peri_wdata[8]} {UMforCPU/peri_wdata[9]} {UMforCPU/peri_wdata[10]} {UMforCPU/peri_wdata[11]} {UMforCPU/peri_wdata[12]} {UMforCPU/peri_wdata[13]} {UMforCPU/peri_wdata[14]} {UMforCPU/peri_wdata[15]} {UMforCPU/peri_wdata[16]} {UMforCPU/peri_wdata[17]} {UMforCPU/peri_wdata[18]} {UMforCPU/peri_wdata[19]} {UMforCPU/peri_wdata[20]} {UMforCPU/peri_wdata[21]} {UMforCPU/peri_wdata[22]} {UMforCPU/peri_wdata[23]} {UMforCPU/peri_wdata[24]} {UMforCPU/peri_wdata[25]} {UMforCPU/peri_wdata[26]} {UMforCPU/peri_wdata[27]} {UMforCPU/peri_wdata[28]} {UMforCPU/peri_wdata[29]} {UMforCPU/peri_wdata[30]} {UMforCPU/peri_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 3 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {UMforCPU/wren_p[0]} {UMforCPU/wren_p[1]} {UMforCPU/wren_p[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 4 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {UMforCPU/peri_wstrb[0]} {UMforCPU/peri_wstrb[1]} {UMforCPU/peri_wstrb[2]} {UMforCPU/peri_wstrb[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 12 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {UMforCPU/wstrb_p[0]} {UMforCPU/wstrb_p[1]} {UMforCPU/wstrb_p[2]} {UMforCPU/wstrb_p[3]} {UMforCPU/wstrb_p[4]} {UMforCPU/wstrb_p[5]} {UMforCPU/wstrb_p[6]} {UMforCPU/wstrb_p[7]} {UMforCPU/wstrb_p[8]} {UMforCPU/wstrb_p[9]} {UMforCPU/wstrb_p[10]} {UMforCPU/wstrb_p[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 134 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {pktData_gmii[0]} {pktData_gmii[1]} {pktData_gmii[2]} {pktData_gmii[3]} {pktData_gmii[4]} {pktData_gmii[5]} {pktData_gmii[6]} {pktData_gmii[7]} {pktData_gmii[8]} {pktData_gmii[9]} {pktData_gmii[10]} {pktData_gmii[11]} {pktData_gmii[12]} {pktData_gmii[13]} {pktData_gmii[14]} {pktData_gmii[15]} {pktData_gmii[16]} {pktData_gmii[17]} {pktData_gmii[18]} {pktData_gmii[19]} {pktData_gmii[20]} {pktData_gmii[21]} {pktData_gmii[22]} {pktData_gmii[23]} {pktData_gmii[24]} {pktData_gmii[25]} {pktData_gmii[26]} {pktData_gmii[27]} {pktData_gmii[28]} {pktData_gmii[29]} {pktData_gmii[30]} {pktData_gmii[31]} {pktData_gmii[32]} {pktData_gmii[33]} {pktData_gmii[34]} {pktData_gmii[35]} {pktData_gmii[36]} {pktData_gmii[37]} {pktData_gmii[38]} {pktData_gmii[39]} {pktData_gmii[40]} {pktData_gmii[41]} {pktData_gmii[42]} {pktData_gmii[43]} {pktData_gmii[44]} {pktData_gmii[45]} {pktData_gmii[46]} {pktData_gmii[47]} {pktData_gmii[48]} {pktData_gmii[49]} {pktData_gmii[50]} {pktData_gmii[51]} {pktData_gmii[52]} {pktData_gmii[53]} {pktData_gmii[54]} {pktData_gmii[55]} {pktData_gmii[56]} {pktData_gmii[57]} {pktData_gmii[58]} {pktData_gmii[59]} {pktData_gmii[60]} {pktData_gmii[61]} {pktData_gmii[62]} {pktData_gmii[63]} {pktData_gmii[64]} {pktData_gmii[65]} {pktData_gmii[66]} {pktData_gmii[67]} {pktData_gmii[68]} {pktData_gmii[69]} {pktData_gmii[70]} {pktData_gmii[71]} {pktData_gmii[72]} {pktData_gmii[73]} {pktData_gmii[74]} {pktData_gmii[75]} {pktData_gmii[76]} {pktData_gmii[77]} {pktData_gmii[78]} {pktData_gmii[79]} {pktData_gmii[80]} {pktData_gmii[81]} {pktData_gmii[82]} {pktData_gmii[83]} {pktData_gmii[84]} {pktData_gmii[85]} {pktData_gmii[86]} {pktData_gmii[87]} {pktData_gmii[88]} {pktData_gmii[89]} {pktData_gmii[90]} {pktData_gmii[91]} {pktData_gmii[92]} {pktData_gmii[93]} {pktData_gmii[94]} {pktData_gmii[95]} {pktData_gmii[96]} {pktData_gmii[97]} {pktData_gmii[98]} {pktData_gmii[99]} {pktData_gmii[100]} {pktData_gmii[101]} {pktData_gmii[102]} {pktData_gmii[103]} {pktData_gmii[104]} {pktData_gmii[105]} {pktData_gmii[106]} {pktData_gmii[107]} {pktData_gmii[108]} {pktData_gmii[109]} {pktData_gmii[110]} {pktData_gmii[111]} {pktData_gmii[112]} {pktData_gmii[113]} {pktData_gmii[114]} {pktData_gmii[115]} {pktData_gmii[116]} {pktData_gmii[117]} {pktData_gmii[118]} {pktData_gmii[119]} {pktData_gmii[120]} {pktData_gmii[121]} {pktData_gmii[122]} {pktData_gmii[123]} {pktData_gmii[124]} {pktData_gmii[125]} {pktData_gmii[126]} {pktData_gmii[127]} {pktData_gmii[128]} {pktData_gmii[129]} {pktData_gmii[130]} {pktData_gmii[131]} {pktData_gmii[132]} {pktData_gmii[133]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 134 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {pktData_um[0]} {pktData_um[1]} {pktData_um[2]} {pktData_um[3]} {pktData_um[4]} {pktData_um[5]} {pktData_um[6]} {pktData_um[7]} {pktData_um[8]} {pktData_um[9]} {pktData_um[10]} {pktData_um[11]} {pktData_um[12]} {pktData_um[13]} {pktData_um[14]} {pktData_um[15]} {pktData_um[16]} {pktData_um[17]} {pktData_um[18]} {pktData_um[19]} {pktData_um[20]} {pktData_um[21]} {pktData_um[22]} {pktData_um[23]} {pktData_um[24]} {pktData_um[25]} {pktData_um[26]} {pktData_um[27]} {pktData_um[28]} {pktData_um[29]} {pktData_um[30]} {pktData_um[31]} {pktData_um[32]} {pktData_um[33]} {pktData_um[34]} {pktData_um[35]} {pktData_um[36]} {pktData_um[37]} {pktData_um[38]} {pktData_um[39]} {pktData_um[40]} {pktData_um[41]} {pktData_um[42]} {pktData_um[43]} {pktData_um[44]} {pktData_um[45]} {pktData_um[46]} {pktData_um[47]} {pktData_um[48]} {pktData_um[49]} {pktData_um[50]} {pktData_um[51]} {pktData_um[52]} {pktData_um[53]} {pktData_um[54]} {pktData_um[55]} {pktData_um[56]} {pktData_um[57]} {pktData_um[58]} {pktData_um[59]} {pktData_um[60]} {pktData_um[61]} {pktData_um[62]} {pktData_um[63]} {pktData_um[64]} {pktData_um[65]} {pktData_um[66]} {pktData_um[67]} {pktData_um[68]} {pktData_um[69]} {pktData_um[70]} {pktData_um[71]} {pktData_um[72]} {pktData_um[73]} {pktData_um[74]} {pktData_um[75]} {pktData_um[76]} {pktData_um[77]} {pktData_um[78]} {pktData_um[79]} {pktData_um[80]} {pktData_um[81]} {pktData_um[82]} {pktData_um[83]} {pktData_um[84]} {pktData_um[85]} {pktData_um[86]} {pktData_um[87]} {pktData_um[88]} {pktData_um[89]} {pktData_um[90]} {pktData_um[91]} {pktData_um[92]} {pktData_um[93]} {pktData_um[94]} {pktData_um[95]} {pktData_um[96]} {pktData_um[97]} {pktData_um[98]} {pktData_um[99]} {pktData_um[100]} {pktData_um[101]} {pktData_um[102]} {pktData_um[103]} {pktData_um[104]} {pktData_um[105]} {pktData_um[106]} {pktData_um[107]} {pktData_um[108]} {pktData_um[109]} {pktData_um[110]} {pktData_um[111]} {pktData_um[112]} {pktData_um[113]} {pktData_um[114]} {pktData_um[115]} {pktData_um[116]} {pktData_um[117]} {pktData_um[118]} {pktData_um[119]} {pktData_um[120]} {pktData_um[121]} {pktData_um[122]} {pktData_um[123]} {pktData_um[124]} {pktData_um[125]} {pktData_um[126]} {pktData_um[127]} {pktData_um[128]} {pktData_um[129]} {pktData_um[130]} {pktData_um[131]} {pktData_um[132]} {pktData_um[133]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 96 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {UMforCPU/dout_32b_p[0]} {UMforCPU/dout_32b_p[1]} {UMforCPU/dout_32b_p[2]} {UMforCPU/dout_32b_p[3]} {UMforCPU/dout_32b_p[4]} {UMforCPU/dout_32b_p[5]} {UMforCPU/dout_32b_p[6]} {UMforCPU/dout_32b_p[7]} {UMforCPU/dout_32b_p[8]} {UMforCPU/dout_32b_p[9]} {UMforCPU/dout_32b_p[10]} {UMforCPU/dout_32b_p[11]} {UMforCPU/dout_32b_p[12]} {UMforCPU/dout_32b_p[13]} {UMforCPU/dout_32b_p[14]} {UMforCPU/dout_32b_p[15]} {UMforCPU/dout_32b_p[16]} {UMforCPU/dout_32b_p[17]} {UMforCPU/dout_32b_p[18]} {UMforCPU/dout_32b_p[19]} {UMforCPU/dout_32b_p[20]} {UMforCPU/dout_32b_p[21]} {UMforCPU/dout_32b_p[22]} {UMforCPU/dout_32b_p[23]} {UMforCPU/dout_32b_p[24]} {UMforCPU/dout_32b_p[25]} {UMforCPU/dout_32b_p[26]} {UMforCPU/dout_32b_p[27]} {UMforCPU/dout_32b_p[28]} {UMforCPU/dout_32b_p[29]} {UMforCPU/dout_32b_p[30]} {UMforCPU/dout_32b_p[31]} {UMforCPU/dout_32b_p[32]} {UMforCPU/dout_32b_p[33]} {UMforCPU/dout_32b_p[34]} {UMforCPU/dout_32b_p[35]} {UMforCPU/dout_32b_p[36]} {UMforCPU/dout_32b_p[37]} {UMforCPU/dout_32b_p[38]} {UMforCPU/dout_32b_p[39]} {UMforCPU/dout_32b_p[40]} {UMforCPU/dout_32b_p[41]} {UMforCPU/dout_32b_p[42]} {UMforCPU/dout_32b_p[43]} {UMforCPU/dout_32b_p[44]} {UMforCPU/dout_32b_p[45]} {UMforCPU/dout_32b_p[46]} {UMforCPU/dout_32b_p[47]} {UMforCPU/dout_32b_p[48]} {UMforCPU/dout_32b_p[49]} {UMforCPU/dout_32b_p[50]} {UMforCPU/dout_32b_p[51]} {UMforCPU/dout_32b_p[52]} {UMforCPU/dout_32b_p[53]} {UMforCPU/dout_32b_p[54]} {UMforCPU/dout_32b_p[55]} {UMforCPU/dout_32b_p[56]} {UMforCPU/dout_32b_p[57]} {UMforCPU/dout_32b_p[58]} {UMforCPU/dout_32b_p[59]} {UMforCPU/dout_32b_p[60]} {UMforCPU/dout_32b_p[61]} {UMforCPU/dout_32b_p[62]} {UMforCPU/dout_32b_p[63]} {UMforCPU/dout_32b_p[64]} {UMforCPU/dout_32b_p[65]} {UMforCPU/dout_32b_p[66]} {UMforCPU/dout_32b_p[67]} {UMforCPU/dout_32b_p[68]} {UMforCPU/dout_32b_p[69]} {UMforCPU/dout_32b_p[70]} {UMforCPU/dout_32b_p[71]} {UMforCPU/dout_32b_p[72]} {UMforCPU/dout_32b_p[73]} {UMforCPU/dout_32b_p[74]} {UMforCPU/dout_32b_p[75]} {UMforCPU/dout_32b_p[76]} {UMforCPU/dout_32b_p[77]} {UMforCPU/dout_32b_p[78]} {UMforCPU/dout_32b_p[79]} {UMforCPU/dout_32b_p[80]} {UMforCPU/dout_32b_p[81]} {UMforCPU/dout_32b_p[82]} {UMforCPU/dout_32b_p[83]} {UMforCPU/dout_32b_p[84]} {UMforCPU/dout_32b_p[85]} {UMforCPU/dout_32b_p[86]} {UMforCPU/dout_32b_p[87]} {UMforCPU/dout_32b_p[88]} {UMforCPU/dout_32b_p[89]} {UMforCPU/dout_32b_p[90]} {UMforCPU/dout_32b_p[91]} {UMforCPU/dout_32b_p[92]} {UMforCPU/dout_32b_p[93]} {UMforCPU/dout_32b_p[94]} {UMforCPU/dout_32b_p[95]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 3 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {UMforCPU/bus/wren_o[0]} {UMforCPU/bus/wren_o[1]} {UMforCPU/bus/wren_o[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 16 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {UMforCPU/bus/peri_addr_test[0]} {UMforCPU/bus/peri_addr_test[1]} {UMforCPU/bus/peri_addr_test[2]} {UMforCPU/bus/peri_addr_test[3]} {UMforCPU/bus/peri_addr_test[4]} {UMforCPU/bus/peri_addr_test[5]} {UMforCPU/bus/peri_addr_test[6]} {UMforCPU/bus/peri_addr_test[7]} {UMforCPU/bus/peri_addr_test[8]} {UMforCPU/bus/peri_addr_test[9]} {UMforCPU/bus/peri_addr_test[10]} {UMforCPU/bus/peri_addr_test[11]} {UMforCPU/bus/peri_addr_test[12]} {UMforCPU/bus/peri_addr_test[13]} {UMforCPU/bus/peri_addr_test[14]} {UMforCPU/bus/peri_addr_test[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 3 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {UMforCPU/bus/pre_wr_rd[0]} {UMforCPU/bus/pre_wr_rd[1]} {UMforCPU/bus/pre_wr_rd[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 3 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {UMforCPU/bus/rden_o[0]} {UMforCPU/bus/rden_o[1]} {UMforCPU/bus/rden_o[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 96 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {UMforCPU/bus/addr_32b_o[0]} {UMforCPU/bus/addr_32b_o[1]} {UMforCPU/bus/addr_32b_o[2]} {UMforCPU/bus/addr_32b_o[3]} {UMforCPU/bus/addr_32b_o[4]} {UMforCPU/bus/addr_32b_o[5]} {UMforCPU/bus/addr_32b_o[6]} {UMforCPU/bus/addr_32b_o[7]} {UMforCPU/bus/addr_32b_o[8]} {UMforCPU/bus/addr_32b_o[9]} {UMforCPU/bus/addr_32b_o[10]} {UMforCPU/bus/addr_32b_o[11]} {UMforCPU/bus/addr_32b_o[12]} {UMforCPU/bus/addr_32b_o[13]} {UMforCPU/bus/addr_32b_o[14]} {UMforCPU/bus/addr_32b_o[15]} {UMforCPU/bus/addr_32b_o[16]} {UMforCPU/bus/addr_32b_o[17]} {UMforCPU/bus/addr_32b_o[18]} {UMforCPU/bus/addr_32b_o[19]} {UMforCPU/bus/addr_32b_o[20]} {UMforCPU/bus/addr_32b_o[21]} {UMforCPU/bus/addr_32b_o[22]} {UMforCPU/bus/addr_32b_o[23]} {UMforCPU/bus/addr_32b_o[24]} {UMforCPU/bus/addr_32b_o[25]} {UMforCPU/bus/addr_32b_o[26]} {UMforCPU/bus/addr_32b_o[27]} {UMforCPU/bus/addr_32b_o[28]} {UMforCPU/bus/addr_32b_o[29]} {UMforCPU/bus/addr_32b_o[30]} {UMforCPU/bus/addr_32b_o[31]} {UMforCPU/bus/addr_32b_o[32]} {UMforCPU/bus/addr_32b_o[33]} {UMforCPU/bus/addr_32b_o[34]} {UMforCPU/bus/addr_32b_o[35]} {UMforCPU/bus/addr_32b_o[36]} {UMforCPU/bus/addr_32b_o[37]} {UMforCPU/bus/addr_32b_o[38]} {UMforCPU/bus/addr_32b_o[39]} {UMforCPU/bus/addr_32b_o[40]} {UMforCPU/bus/addr_32b_o[41]} {UMforCPU/bus/addr_32b_o[42]} {UMforCPU/bus/addr_32b_o[43]} {UMforCPU/bus/addr_32b_o[44]} {UMforCPU/bus/addr_32b_o[45]} {UMforCPU/bus/addr_32b_o[46]} {UMforCPU/bus/addr_32b_o[47]} {UMforCPU/bus/addr_32b_o[48]} {UMforCPU/bus/addr_32b_o[49]} {UMforCPU/bus/addr_32b_o[50]} {UMforCPU/bus/addr_32b_o[51]} {UMforCPU/bus/addr_32b_o[52]} {UMforCPU/bus/addr_32b_o[53]} {UMforCPU/bus/addr_32b_o[54]} {UMforCPU/bus/addr_32b_o[55]} {UMforCPU/bus/addr_32b_o[56]} {UMforCPU/bus/addr_32b_o[57]} {UMforCPU/bus/addr_32b_o[58]} {UMforCPU/bus/addr_32b_o[59]} {UMforCPU/bus/addr_32b_o[60]} {UMforCPU/bus/addr_32b_o[61]} {UMforCPU/bus/addr_32b_o[62]} {UMforCPU/bus/addr_32b_o[63]} {UMforCPU/bus/addr_32b_o[64]} {UMforCPU/bus/addr_32b_o[65]} {UMforCPU/bus/addr_32b_o[66]} {UMforCPU/bus/addr_32b_o[67]} {UMforCPU/bus/addr_32b_o[68]} {UMforCPU/bus/addr_32b_o[69]} {UMforCPU/bus/addr_32b_o[70]} {UMforCPU/bus/addr_32b_o[71]} {UMforCPU/bus/addr_32b_o[72]} {UMforCPU/bus/addr_32b_o[73]} {UMforCPU/bus/addr_32b_o[74]} {UMforCPU/bus/addr_32b_o[75]} {UMforCPU/bus/addr_32b_o[76]} {UMforCPU/bus/addr_32b_o[77]} {UMforCPU/bus/addr_32b_o[78]} {UMforCPU/bus/addr_32b_o[79]} {UMforCPU/bus/addr_32b_o[80]} {UMforCPU/bus/addr_32b_o[81]} {UMforCPU/bus/addr_32b_o[82]} {UMforCPU/bus/addr_32b_o[83]} {UMforCPU/bus/addr_32b_o[84]} {UMforCPU/bus/addr_32b_o[85]} {UMforCPU/bus/addr_32b_o[86]} {UMforCPU/bus/addr_32b_o[87]} {UMforCPU/bus/addr_32b_o[88]} {UMforCPU/bus/addr_32b_o[89]} {UMforCPU/bus/addr_32b_o[90]} {UMforCPU/bus/addr_32b_o[91]} {UMforCPU/bus/addr_32b_o[92]} {UMforCPU/bus/addr_32b_o[93]} {UMforCPU/bus/addr_32b_o[94]} {UMforCPU/bus/addr_32b_o[95]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 8 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {UMforCPU/rs485_inst_1/rs485_dataRx[0]} {UMforCPU/rs485_inst_1/rs485_dataRx[1]} {UMforCPU/rs485_inst_1/rs485_dataRx[2]} {UMforCPU/rs485_inst_1/rs485_dataRx[3]} {UMforCPU/rs485_inst_1/rs485_dataRx[4]} {UMforCPU/rs485_inst_1/rs485_dataRx[5]} {UMforCPU/rs485_inst_1/rs485_dataRx[6]} {UMforCPU/rs485_inst_1/rs485_dataRx[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 8 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {UMforCPU/rs485_inst_1/rs485_dataTx[0]} {UMforCPU/rs485_inst_1/rs485_dataTx[1]} {UMforCPU/rs485_inst_1/rs485_dataTx[2]} {UMforCPU/rs485_inst_1/rs485_dataTx[3]} {UMforCPU/rs485_inst_1/rs485_dataTx[4]} {UMforCPU/rs485_inst_1/rs485_dataTx[5]} {UMforCPU/rs485_inst_1/rs485_dataTx[6]} {UMforCPU/rs485_inst_1/rs485_dataTx[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list UMforCPU/timelyRV_top/mem_instr]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list UMforCPU/timelyRV_top/mem_rden]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list UMforCPU/timelyRV_top/mem_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list UMforCPU/timelyRV_top/mem_ready_mem]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list UMforCPU/timelyRV_top/mem_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list UMforCPU/timelyRV_top/mem_wren]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list UMforCPU/peri_rden]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list UMforCPU/peri_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list UMforCPU/peri_wren]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list pktData_valid_gmii]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list pktData_valid_um]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list UMforCPU/rs485_inst_1/rs485_dataRx_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list UMforCPU/rs485_inst_1/rs485_dataTx_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list UMforCPU/rs485_inst_1/rs485_tx_busy_o]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list UMforCPU/rs485_inst_1/rxclk_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list UMforCPU/timelyRV_top/trap]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list UMforCPU/rs485_inst_1/txclk_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_125m]
